### ISSUE TITLE
Crash when changing lamp settings

### ISSUE THREAD

**Issue by mkaito** [Ben-Ramchandani/OutpostPlanner#10]
When changing lamps to place every X blueprints, this happens:

![factorio_crash_outpost_planner](https://user-images.githubusercontent.com/20434/33899485-8a048560-df63-11e7-88ec-566505255e16.png)

**Comment by Ben-Ramchandani** [comment]
Hmm this actually seems to be a bug in Upgrade Planner, I'll have another look in the morning and see if I can do anything on my end and maybe put in a bug report on Upgrade Planner.

For now if you open and close the Upgrade Planner window (U or the little button) it will set itself up and the crash shouldn't happen.

**Comment by Ben-Ramchandani** [comment]
Looks like this will be fixed in the 0.16 version of Upgrade Planner when the next version of Factorio is released (which should be soon).

https://forums.factorio.com/viewtopic.php?f=92&t=14781&start=260#p310653

I'll leave this issue open until 0.16 is released, but I don't think I can do anything about it.

**Comment by Ben-Ramchandani** [comment]
Looks like this is fixed in 0.16.
