### ISSUE TITLE
Pole is shifted 1 tiles if the Orientation is South or West

### ISSUE THREAD

**Issue by minyan** [Ben-Ramchandani/OutpostPlanner#4]
Hard to describe in words, so i attach an image instead.
![untitled](https://user-images.githubusercontent.com/829593/27811941-63538c10-6095-11e7-8a3f-20f287399bda.png)

Basically what OP did was placed the mining drill correctly, but then the pole is shifted 1 tiles, so the result is some mining drill being override. 

This is not happening in other orientation (North/East)

**Comment by Ben-Ramchandani** [comment]
Thank you very much for the report, this is fixed in 0.1.5.

**Comment by Ben-Ramchandani** [comment]
If you're interested in why:

It was actually the miners and the belts that were being placed incorrectly, but the poles were also being placed incorrectly until a version or two ago so I didn't notice :)

In Factorio 1x1 and 3x3 entities have their centres at (<>.5, <>.5) so that their corners/edges align with the grid. I was placing them at (<>.0, <>.0) and Factorio automatically moved them by (0.5, 0.5) to align them. This meant that when the co-ordinates were rotated the entities ended up one tile off. The entities are now placed correctly at (<>.5, <>.5) so this isn't an issue.

Thank you again and hope you're finding the mod useful.

**Comment by minyan** [comment]
Thank you, 
And it's always good to know the reason why the bug happening.
